# Generated by Django 4.2.5 on 2023-09-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.UUIDField(default='volki', editable=False, primary_key=True, serialize=False),
        ),
    ]
