# Generated by Django 4.2.5 on 2023-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0002_alter_advertisement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=128, verbose_name='заголовок'),
        ),
    ]
