# Generated by Django 4.2.5 on 2023-09-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0003_rename_create_at_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
