# Generated by Django 4.2.5 on 2023-09-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0003_alter_advertisement_id_alter_advertisement_table'),
        ('app_advertisments', '0004_rename_created_at_advertisement_create_at_and_more'),
    ]

    operations = [
    ]
