# Generated by Django 4.2.5 on 2023-10-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0006_alter_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='advertisments/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
