# Generated by Django 4.2.5 on 2023-10-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0005_merge_20230929_2129'),
        ('app_advertisments', '0007_advertisement_image'),
    ]

    operations = [
    ]
